### DISCUSSION TITLE
ClientError: The security token included in the request is invalid.

### DISCUSSION THREAD

**Discussion by OFilipovs** [saleweaver/python-amazon-sp-api#109] [Q&A]
Hello

I am having trouble with authentication. 

I get this error:

"ClientError: An error occurred (InvalidClientTokenId) when calling the AssumeRole operation: The security token included in the request is invalid."

Can you point me in the direction where my credentials are wrong, since I am new to AWS.

Thank you

**Comment by FA5I** [comment]
This means that you have a wrong value for one of the fields in the config.yaml file you created:

```
  refresh_token: 
  lwa_app_id: 
  lwa_client_secret: 
  aws_secret_key: 
  aws_access_key: 
  role_arn: 
```

The issue is you appeared to have the wrong `lwa_app_id` I think
